---
functional:
  - Пользователь должен иметь возможность регистрации через e-mail
  - Пользователь должен иметь возможность авторизации через e-mail
  - Пользователь должен иметь возможность авторизации через github
  - Пользователь должен иметь возможность авторизации через discord
  - Пользователь должен иметь возможность соревноваться с другим человеком
  - Пользователь должен иметь возможность соревноваться с ботом
  - Должен быть предусмотрен выбор уровня сложности задачи
  - Должен быть предусмотрен выбор задачи из списка
  - Должен быть предусмотрен фильтр задач по тегам
  - Должен быть предусмотрен таймер раунда и его выбор
  - Пользователь должен иметь возможность подключиться к игровому процессу в качестве спектатора
  - Пользователь возможность сдаться в игре, с наличием соответствующей кнопки в интерфейсе
  - Пользователь не должен иметь возможности копировать код из окна редактора оппонента
  - Пользователь должен иметь возможность выбрать язык программирования
  - При победе/поражении/сдаче/ничье должно выводиться соответствующее сообщение
  - Должно быть предусмотрено окно вывода результатов проверки кода и показом задания в разных табах
  - Должен быть предусмотрен общий чат, а так же уникальный чат для каждой игры
  - На главной странице должен быть предусмотрен блок с текущими играми, турнирами и списком завершенных игр
  - Должна быть предусмотрена страница профиля с указанием статистики, списком завершенных игр и выполненными достижениями
  - Должен быть предусмотрена страница с рейтингом пользователей
non-functional:
  -  Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  -  Сайт должен быть безопасным и защищать данные пользователя
  -  Сайт должен быть удобным на мобильном устройстве
  -  Сайт должен быть протестирован на совместимость с последними версиями браузеров
  -  Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Должна быть предусмотрена возможность выбора языка локализации на сайте
  - Должны быть предусмотрена страница со списком достижений (Achievements), с отметкой о выполненных/не выполненных достижениях
